# Test intermedio: comprueba lo que has aprendido

1. La parte del código donde se cree que puede ocurrir una excepción debe colocarse dentro:
  
    * De un bloque `try:`
    * De un bloque `except:`
    * De un bloque `exception:`

2. La parte del código donde se lleva a cabo el manejo de una excepción debe colocarse dentro:

    * De un bloque `try:`
    * De un bloque `except:`
    * De un bloque `exception:`

3. Elige las sentencias verdaderas. (Selecciona dos respuestas):

    * [ ] Se pueden emplear múltiples bloques `except:` para manejar múltiples excepciones provenientes del mismo bloque `try:`
    * [ ] No se pueden emplear múltiples bloques `except:` para manejar múltiples excepciones provenientes del mismo bloque `try:`
    * [ ] Diferentes bloques `exception:` deben tener nombres de excepción únicos
    * [ ] Diferentes bloques `exception:` pueden tener nombres de excepción únicos

4. Cuando ocurre una excepción, decimos que ha sido:

    * Generada
    * Probada
    * Caida

5. ¿Cuál de los bloques accesibles de `except:` se toma en consideración cuando ocurre una excepción?:

    * El primer bloque coincidente
    * El último bloque coincidente
    * Cualquiera de los bloques coincidente

6. Una aserción se puede utilizar para:

    * Detener el programa cuando algunos de los datos contengan valores incorrectos
    * Hacer que el programador sea m\u00e1s asertivo
    * Importar un módulo

7. Un punto de código es:

    * Un número que compone un carácter
    * Un punto empleado para escribir código
    * Un código que contiene un punto

8. `isalnum()` comprueba si una cadena contiene solo letras y dígitos, y esto es:

    * Un método
    * Un módulo
    * Una función

9. La expresión:
    ```
    'mike' > 'Mike'
    ```

    * Se evalúa a `True`
    * Se evalúa a `False`
    * Es errónea

10. El operador `+=`, cuando se aplica en cadenas, realiza:

    * Concatenación
    * Multiplicación
    * Sustracción
